-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 17:07:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDG
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BDG` ;

-- -----------------------------------------------------
-- Schema BDG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDG` DEFAULT CHARACTER SET utf8 ;
USE `BDG` ;

-- -----------------------------------------------------
-- Table `BDG`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDG`.`User` ;

CREATE TABLE IF NOT EXISTS `BDG`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(70) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `BDG`.`Entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDG`.`Entries` ;

CREATE TABLE IF NOT EXISTS `BDG`.`Entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `text` VARCHAR(10000) NULL,
  `image` VARCHAR(255) NULL,
  `number` INT NULL,
  PRIMARY KEY (`id`))
CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BDG`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDG`;
INSERT INTO `BDG`.`User` (`id`, `login`, `password`, `role`) VALUES (1, 'Admin', '$2a$10$Xgp47yiwVrJGZSqcu6pRUei69ak8okFIFGO1EE2fdk4qNCbB93Bzq', 'ADMIN');
INSERT INTO `BDG`.`User` (`id`, `login`, `password`, `role`) VALUES (2, 'User', '$2a$12$FKekHYTqCdYSzoVZwNB/8OmnRHuHdPS7HHHfXEcEnmVgFXTW/WBh.', 'USER');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDG`.`Entries`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDG`;
INSERT INTO `BDG`.`Entries` (`id`, `date`, `text`, `image`, `number`) VALUES (DEFAULT, '2022-01-20', 'Над Беларуссю Сонца марудна ўстае, I спяшаецца за навалай навала. Адам Міцкевіч паліць Беларускія вершы свае, Каб напісаў іх Янка Купала... ', 'images/1.jpg', 123454);
INSERT INTO `BDG`.`Entries` (`id`, `date`, `text`, `image`, `number`) VALUES (DEFAULT, '2022-03-20', 'Прыціхлая прырода засынае, Прыносіць лістапад спакой. Апошні ліст з галін злятае, Апошні сведка квецені былой. І ў люстры белае вады глядзяцца з сумам камышы, ім баюць казкі халады пра адпачынак ў цішы.  І шэры лес стаіць у тумане, Ён размаўляе сам з сабою: “вясна – гэта жыцця світанне, дзень – лета, восень - час спакою”', 'images/2.jpg', -1);
INSERT INTO `BDG`.`Entries` (`id`, `date`, `text`, `image`, `number`) VALUES (DEFAULT, '2022-02-20', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra adipiscing at in tellus integer. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Suspendisse ultrices gravida dictum fusce. Consectetur lorem donec massa sapien. Egestas purus viverra accumsan in nisl nisi. A cras semper auctor neque. Cras semper auctor neque vitae tempus quam pellentesque. Massa placerat duis ultricies lacus sed turpis tincidunt id. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Vel turpis nunc eget lorem dolor sed.', 'images/3.jpg', 01234);
INSERT INTO `BDG`.`Entries` (`id`, `date`, `text`, `image`, `number`) VALUES (DEFAULT, '2022-11-20', NULL, NULL, 987654);


COMMIT;

